apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-git
spec:
  type: git
  params:
    - name: revision
      value: release/v1.2.0
    - name: url
      value: https://github.com/GoogleContainerTools/skaffold
    - name: httpsProxy
      value: ""
